### ISSUE TITLE
不起作用哦

### ISSUE THREAD

**Issue by parcool** [BolexLiu/ReciteWords#1]
已安装，已重启。没法提示，也没找到.MD。难道是因为我安装了有道桌面版？

**Comment by BolexLiu** [comment]
能否提供as版本，我看下

**Comment by parcool** [comment]
as 2.3

**Comment by parcool** [comment]
也有可能是我电脑问题。我其他有些插件也用不了呢

**Comment by BolexLiu** [comment]
上周也有一个小伙伴说2.3用不了。但是我后面已经修复了那个bug。最后他测试运行过后是没有问题的。当时2.3的bug是由于没有包名的插件引起的。

**Comment by BolexLiu** [comment]
@parcool  邀请您更新到1.2的版本。已修复这些bug
