### ISSUE TITLE
Mac does not work, Permission denied

### ISSUE THREAD

**Issue by WenkaiZhou** [BolexLiu/ReciteWords#2]
Mac does not work, Permission denied

**Comment by BolexLiu** [comment]
Solving this bug！

**Comment by jorry** [comment]
+1

**Comment by BolexLiu** [comment]
已经解决了报权限不足的问题，那是由于在mac或linux下无法写入io。你可以把你用户目录权限改为777，请安装新的版本。已上传

**Comment by wb12581** [comment]
+1

**Comment by BolexLiu** [comment]
1.2版本更新后，不需要修改目录权限了。 因为文档将直接生成在当前项目的根路径下。
